version: '3'

services:
  nginx:
    build: ./src/requirements/nginx
    restart: always
    ports:
      - "127.0.0.1:8000:80"
      # - "127.0.0.1:8000:443"
#     volumes:
#       - wordpress_files:/var/www/html
    # networks:
    #   - app-network

#   wordpress:
#     build: ./wordpress
#     restart: always
#     volumes:
#       - wordpress_files:/var/www/html
#     networks:
#       - app-network

#   mariadb:
#     build: ./mariadb
#     restart: always
#     volumes:
#       - wordpress_db:/var/lib/mysql
#     networks:
#       - app-network

# volumes:
#   wordpress_files:
#   wordpress_db:

# networks:
#   app-network:
