version: '3.9'

services:
  app:
    container_name: wordpress
    build:
      context: .
      dockerfile: /sraza/Desktop/inception/wordpresss/Dockerfile
    volumes:
      - ./aaplication:/code
      - ./static:/static
    ports:
      - '8000:8000'
      # port for debug
      - '8008:8080'
    command: sh -c "/usr/local/bin/entrypoint.sh"
    stdin_open: true
    tty: true
    env_file:
      - .env

    nginx:
      container_name:nginx
      build:
        context:
          dockerfile:/sraza/Desktop/inception/nginx/dockerfile
