services:
  mariadb:
    container_name: mariadb
    networks:
      - inception-sraza-network
    build:
      context: ./requirements/mariadb
    env_file: .env
    # volumes:
    #   - db:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"

  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
    restart: always
    ports:
      - "127.0.0.1:443:443"
    # volumes:
    #   - web:/var/www/html
    depends_on:
      - wordpress
    networks:
      - inception-sraza-network

  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress
    # volumes:
    #   - web:/var/www/html
    ports:
      - "9000:9000"
    depends_on:
      - mariadb
    env_file:
      - .env
    restart: always
    entrypoint: sh -c "chmod +x /var/www/html/auto_config.sh && /var/www/html/auto_config.sh"
    networks:
      - inception-sraza-network


networks:
  inception-sraza-network:
    name: inception-sraza-network
# volumes:
#   db:
#     driver_opts:
#       type: local
#       device: ${VOLUME_DB}
#       o: bind
#   web:
#     driver_opts:
#       type: local
#       device: ${VOLUME_WEB}
#       o: bind