services:
  nginx:
    build:
      context: ./requirements/nginx
    restart: always
    ports:
      - "443:443"
    volumes:
      - web:/var/www/html
    depends_on:
      - wordpress
    networks:
      - inception-sraza-network

  mariadb:
    build:
      context: ./requirements/mariadb
    environment:
      MYSQL_DB_NAME: "${MYSQL_DB_NAME}"
      MYSQL_ROOT_PW: "${MYSQL_ROOT_PW}"
      MYSQL_USER_NAME: "${MYSQL_USER_NAME}"
      MYSQL_USER_PW: "${MYSQL_USER_PW}"
    volumes:
      - db:/var/lib/mysql
    ports:
      - "3306:3306"
    command: sh -c "if [ ! -d /var/lib/mysql/mysql ]; then mysql_install_db --user=mysql --datadir=/var/lib/mysql; fi && /usr/local/bin/setup_db.sh && exec mysqld --defaults-file=/etc/mysql/mariadb.conf.d/50-server.cnf --innodb_use_native_aio=0"
    restart: always
    networks:
      - inception-sraza-network

  wordpress:
    build:
      context: ./requirements/wordpress
    volumes:
      - web:/var/www/html
      # - ./requirements/wordpress/conf/auto_config.sh:/var/www/html/auto_config.sh
    ports:
      - "9000:9000"
    depends_on:
      - mariadb
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_NAME: "${MYSQL_DB_NAME}"
      WORDPRESS_DB_USER: "${MYSQL_USER_NAME}"
      WORDPRESS_DB_PASSWORD: "${MYSQL_USER_PW}"
    restart: always
    entrypoint: sh -c "chmod +x /var/www/html/auto_config.sh && /var/www/html/auto_config.sh"
    networks:
      - inception-sraza-network

volumes:
  db:
    driver_opts:
      type: local
      device: ${VOLUME_DB}
      o: bind
  web:
    driver_opts:
      type: local
      device: ${VOLUME_WEB}
      o: bind

networks:
  inception-sraza-network:
    name: inception-sraza-network