services:
  mariadb:
    image: mariadb:sraza
    build:
      context: ./requirements/mariadb
    container_name: mariadb
    volumes:
      - db:/var/lib/mysql
    ports:
      - "3306:3306"
    env_file: 
      - .env
    restart: always
    networks:
      - inception-sraza-network

  nginx:
    image: nginx:sraza
    build:
      context: ./requirements/nginx
    container_name: nginx
    depends_on:
      - wordpress
    volumes:
      - web:/var/www/html
    ports:
      - "127.0.0.1:443:443"
    restart: always
    networks:
      - inception-sraza-network

  wordpress:
    image: wordpress:sraza
    build:
      context: ./requirements/wordpress
    container_name: wordpress
    depends_on:
      - mariadb
    volumes:
      - web:/var/www/html
    ports:
      - "9000"
    env_file:
      - .env
    restart: always
    entrypoint: sh -c "chmod +x /var/www/html/auto_config.sh && /var/www/html/auto_config.sh"
    networks:
      - inception-sraza-network

networks:
  inception-sraza-network:
    name: inception-sraza-network
volumes:
  db:
    driver_opts:
      type: local
      device: ${VOLUME_DB}
      o: bind
  web:
    driver_opts:
      type: local
      device: ${VOLUME_WEB}
      o: bind